import path from 'node:path';
import ts from 'typescript';
import {
    formatApiSymbol,
    referencedApiSymbols,
    resolveApiSymbol,
} from './api-symbol-signature.mts';
import { expectedPublicExports } from './public-export-manifest.mts';

const packageNames: Readonly<Record<string, string>> = {
    'src/index.ts': 'smoque',
    'src/plugin.ts': 'smoque/plugin',
};

export interface PublicApiReport {
    report: string;
    diagnostics: string[];
}

export function createPublicApiReport(root: string): PublicApiReport {
    const parsed = readTypeConfig(root);
    if (parsed.diagnostics.length > 0 || parsed.options === undefined) {
        return { report: '', diagnostics: parsed.diagnostics };
    }
    const sourcePaths = Object.keys(expectedPublicExports);
    const program = ts.createProgram({
        rootNames: sourcePaths.map((sourcePath) => path.join(root, sourcePath)),
        options: { ...parsed.options, noEmit: true },
    });
    const checker = program.getTypeChecker();
    const sourceRoot = `${path.join(root, 'src')}${path.sep}`;
    const publicSymbols: Set<ts.Symbol> = new Set();
    const publicNames: Set<string> = new Set();
    const sections: string[] = [];
    const diagnostics: string[] = [];

    for (const sourcePath of sourcePaths) {
        const sourceFile = program.getSourceFile(path.join(root, sourcePath));
        const moduleSymbol = sourceFile === undefined
            ? undefined
            : checker.getSymbolAtLocation(sourceFile);
        if (moduleSymbol === undefined) {
            diagnostics.push(`${sourcePath}: public entrypoint could not be inspected.`);
            continue;
        }
        const exports = checker.getExportsOfModule(moduleSymbol)
            .sort((left, right) => left.name < right.name ? -1 : 1);
        const expected = [...expectedPublicExports[sourcePath] ?? []].sort();
        const actual = exports.map((symbol) => symbol.name);
        if (JSON.stringify(actual) !== JSON.stringify(expected)) {
            diagnostics.push(formatExportFailure(sourcePath, expected, actual));
        }
        const declarations = exports.map((symbol) => {
            const resolved = resolveApiSymbol(symbol, checker);
            publicSymbols.add(resolved);
            publicNames.add(symbol.name);
            return formatReportDeclaration(symbol.name, resolved, checker);
        });
        sections.push(`## ${packageNames[sourcePath] ?? sourcePath}\n\n${declarations.join('\n\n')}`);
    }

    const transitive = collectTransitiveSymbols(
        publicSymbols,
        publicNames,
        checker,
        sourceRoot,
    );
    if (transitive.length > 0) {
        const declarations = transitive.map((symbol) =>
            formatReportDeclaration(symbol.name, symbol, checker));
        sections.push(`## Transitive public types\n\n${declarations.join('\n\n')}`);
    }
    const heading = '# Public API\n\n'
        + '<!-- Generated by npm run api:update. Review every change. -->';
    return {
        report: `${heading}\n\n${sections.join('\n\n')}\n`,
        diagnostics,
    };
}

function collectTransitiveSymbols(
    publicSymbols: ReadonlySet<ts.Symbol>,
    publicNames: ReadonlySet<string>,
    checker: ts.TypeChecker,
    sourceRoot: string,
): ts.Symbol[] {
    const visited = new Set(publicSymbols);
    const queue = [...publicSymbols];
    const transitive: ts.Symbol[] = [];
    for (const symbol of queue) {
        for (const referenced of referencedApiSymbols(symbol, checker, sourceRoot)) {
            if (visited.has(referenced) || publicNames.has(referenced.name)) {
                continue;
            }
            visited.add(referenced);
            queue.push(referenced);
            transitive.push(referenced);
        }
    }
    return transitive.sort((left, right) => left.name < right.name ? -1 : 1);
}

function formatReportDeclaration(
    name: string,
    symbol: ts.Symbol,
    checker: ts.TypeChecker,
): string {
    return `### ${name}\n\n\`\`\`ts\n${formatApiSymbol(name, symbol, checker)}\n\`\`\``;
}

function readTypeConfig(root: string): {
    options?: ts.CompilerOptions;
    diagnostics: string[];
} {
    const configPath = path.join(root, 'tsconfig.base.json');
    const config = ts.readConfigFile(configPath, (file) => ts.sys.readFile(file));
    if (config.error !== undefined) {
        return { diagnostics: [formatDiagnostic(config.error)] };
    }
    const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, root);
    return {
        options: parsed.options,
        diagnostics: parsed.errors.map(formatDiagnostic),
    };
}

function formatExportFailure(
    sourcePath: string,
    expected: readonly string[],
    actual: readonly string[],
): string {
    return [
        `${sourcePath}: public exports changed.`,
        `  expected: ${expected.join(', ')}`,
        `  actual:   ${actual.join(', ')}`,
    ].join('\n');
}

function formatDiagnostic(diagnostic: ts.Diagnostic): string {
    return ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
}
