export const legacyLineLimits: ReadonlyMap<string, number> = new Map([
    ['src/assertions/file/file-expectation.ts', 211],
    ['src/assertions/file/file-set-expectation.ts', 191],
    ['src/cli/commands/doctor.ts', 185],
    ['src/cli/discovery/smoke-files.ts', 159],
    ['src/command/run-command.ts', 223],
    ['src/core/context/smoke-context.ts', 224],
    ['src/core/runner/run-registered-suites.ts', 162],
    ['src/core/runner/suite-executor.ts', 213],
    ['src/plugins/compose/compose-project.ts', 193],
    ['src/plugins/http/client.ts', 333],
    ['src/plugins/http/fake-server.ts', 218],
    ['src/plugins/node/npm-pack.ts', 156],
    ['src/ports.ts', 158],
    ['src/process.ts', 333],
    ['src/reporting/event-report-builder.ts', 293],
    ['src/reporting/junit-reporter.ts', 188],
    ['src/reporting/terminal-reporter.ts', 265],
    ['test/integration/cli/main.test.ts', 1113],
    ['test/unit/assertions/expectations.test.ts', 422],
    ['test/unit/core/plugin-context.test.ts', 386],
    ['test/unit/core/redaction.test.ts', 239],
    ['test/unit/core/runner.test.ts', 289],
    ['test/unit/plugins/archive/archive.test.ts', 158],
    ['test/unit/plugins/compose/compose.test.ts', 267],
    ['test/unit/plugins/http/http.test.ts', 743],
    ['test/unit/plugins/node/node.test.ts', 448],
    ['test/unit/plugins/node/package-metadata.test.ts', 230],
    ['test/unit/plugins/postgres/postgres.test.ts', 449],
    ['test/unit/reporting/reporters.test.ts', 432],
    ['test/unit/runtime/command/command.test.ts', 203],
    ['test/unit/runtime/process-tree.test.ts', 172],
    ['test/unit/runtime/process/process.test.ts', 418],
]);

export const legacyGenericModules: ReadonlySet<string> = new Set([
    'src/types/common.ts',
    'test/integration/cli/helpers.ts',
]);

export const legacySourceIndexes: ReadonlySet<string> = new Set([
    'src/assertions/index.ts',
    'src/command/index.ts',
    'src/network/index.ts',
    'src/plugins/compose/index.ts',
    'src/plugins/http/index.ts',
    'src/plugins/node/index.ts',
    'src/plugins/postgres/index.ts',
    'src/types/index.ts',
]);
